app/blueprints/main/main.py
"""Routes for currency pages."""
import requests
from decimal import Decimal, getcontext
from flask import Blueprint
from flask import current_app as app
from flask import redirect, render_template, session, url_for
from flask_login import current_user, login_required, logout_user

from ...assets import compile_auth_assets
from ..transactions.models import Transaction


main_bp = Blueprint(
    'main_bp',
    __name__,
    template_folder='templates',
    static_folder='static'
)


@main_bp.route("/", methods=["GET"])
@login_required
def home():
    """Homepage route."""
    balances = Transaction.get_all_balances()
    exchange_data = fetch_exchange_rates()
    exchanged_balances = {}
    exchanged_total = 0
    getcontext().prec = 10
    
    
    for balance in balances:

        translated = translate_currency(balance.currency, exchange_data)
        exchanged_balances[balance.currency] = Decimal(balance.total) * Decimal(translated)
        exchanged_total += exchanged_balances[balance.currency] 

    return render_template(
        'index.jinja2',
        balances = balances,
        exchanged_balances = exchanged_balances,
        exchanged_total = exchanged_total,
        title = 'Home | Partner app',
        template = 'home-static main',
        body = "Home"
    )


@main_bp.route("/logout")
@login_required
def logout():
    """User log-out logic."""
    logout_user()
    return redirect(url_for("auth_bp.login"))


def fetch_exchange_rates():
    exchange_rates = requests.get("https://api.hnb.hr/tecajn/v2")
    return exchange_rates.json()

def translate_currency(currency, data):
    if currency != "HRK":
        x = list(filter(lambda x:x["valuta"]==str(currency), data))
        translated = x[0]["srednji_tecaj"].replace(',', '.')
    else:
        translated = 1
    
    return Decimal(translated)

app/templates/layout.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
  {% include 'meta.jinja2' %}
  {% block pagestyles %}{% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,500" rel="stylesheet">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
</head>

<body class="{{template}}">

  {% include "navigation.jinja2" %}


  <div class="grid-row-12">
    {% if current_user.is_authenticated %}
    <div class="grid-col-2">
      {% include "sidebar.jinja2" %}
    </div>
    {% endif %}
    {% if current_user.is_authenticated %}
    <div class="grid-col-7">
    {% else %}
    <div class="grid-col-12">
    {% endif %}
      {% block content %}{% endblock %}
    </div>  
  </div>


  <!-- Scripts -->
  <script src="{{ url_for('static', filename='dist/js/main.min.js') }}"></script>
  {% block scripts %}{% endblock %}
</body>

</html>

app/templates/meta.jinja2
{% block meta %}
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>{{title}}</title>
  <meta name="HandheldFriendly" content="True" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
  <meta name="theme-color" content="#5eb9d7" />
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.png') }}" type="image/x-icon"/>
{% endblock %}

app/templates/navigation.jinja2
<nav class="navigation-default">
  <div class="nav-wrapper">
    <div class="left-nav">
      <img src="{{ url_for('static', filename='img/paba_logo.png') }}" alt="logo" />
    </div>
    <div class="right-nav">
    {% if current_user.is_authenticated %}
      <a href="{{ url_for('main_bp.logout') }}">Logout</a>
    {% endif %}
    </div>
  </div>
</nav>

app/templates/sidebar.jinja2
<aside class="sidebar">
    <a href="{{ url_for('main_bp.home') }}"> <section class="menu_item">Dashboard</section> </a>
    <a href="{{ url_for('transaction_bp.new') }}"> <section class="menu_item">New transaction</section> </a>
    <a href="{{ url_for('transaction_bp.list') }}"> <section class="menu_item">All transactions</section> </a>
    <a href="{{ url_for('stats_bp.stats') }}"> <section class="menu_item">Stastistics</section> </a>
</aside>